### ISSUE TITLE
Incapsula

### ISSUE THREAD

**Issue by toman-tom** [qianyin123/jianyue_md#1]
Hi, please can you share some example source code for your Incapsula example?

https://github.com/qianyin123/jianyue_md/blob/7cb626d9b33f78d2eeb1c45816135854b258cd98/md/incapsula%20%E5%88%86%E6%9E%90.md

**Comment by qianyin123** [comment]
YUhSMGNITTZMeTkzZDNjdWNISnBZMlZzYVc1bExtTnZiUzVoZFM4PQ==
